# -*- coding: utf-8 -*-
"""
Inspirational quotes for academic workers, researchers, and students.
Curated for a warm, modern, gender-neutral tone with cute elements.
"""

# =============================================================================
# 1. Chinese Inspirational / Motivational Quotes (励志语录)
#    Topics: perseverance, self-care, growth, dreams, knowledge
# =============================================================================
CHINESE_INSPIRATIONAL = [
    "你现在的努力，是未来的你会感谢的礼物。",
    "慢慢来，比较快。",
    "没有白走的路，每一步都算数。",
    "你不必很厉害才能开始，但你要开始才能很厉害。",
    "熬过无人问津的日子，才有诗和远方。",
    "生活不会辜负每一个努力向上的人。",
    "保持热爱，奔赴山海。",
    "日拱一卒，功不唐捐。",
    "你的坚持，终将美好。",
    "把每一天都当作一个新的起点。",
    "别害怕走得慢，只要你一直在走。",
    "成长本身就是一种勇气。",
    "星光不负赶路人。",
    "你现在偷的每一份懒，未来都会加倍偿还；你现在流的每一滴汗，未来都会闪闪发光。",
    "世界上最棒的事之一，就是每天都比昨天的自己更强一点。",
    "无论多难，也要告诉自己：再坚持一下。",
    "总有一天，你会感谢那个咬牙坚持的自己。",
    "好好生活，慢慢相遇。",
    "你的努力不会被辜负，时间会给你最好的答案。",
    "所有的光芒，都需要时间才能被看见。",
    "愿你在迷茫时，坚信你的珍贵。",
    "今天的辛苦，是明天的底气。",
    "把自己活成一束光，温暖自己也照亮别人。",
    "每一个优秀的人，都有一段沉默的时光。",
    "你要悄悄拔尖，然后惊艳所有人。",
    "别忘了，你曾经也是第一名——在亿万个生命中率先到达的那一个。",
    "不要让任何人打乱你的节奏，因为没有人比你更清楚自己的方向。",
    "哪怕生活再难，也要记得对自己温柔。",
    "你不是在浪费时间，你是在积蓄力量。",
    "允许自己偶尔偷懒，但别忘了自己的目标。",
    "努力是为了将来的自己，有更多选择的权利。",
    "今天很难，但明天会更好。",
    "你值得拥有你梦想中的一切。",
    "人生没有白读的书，每一页都有意义。",
    "你的气质里，藏着你走过的路、读过的书、爱过的人。",
    "知识是唯一不会被辜负的投资。",
    "你只管努力，剩下的交给时间。",
    "别人都在努力，你也不能落后——但也别忘了好好吃饭。",
    "学到的知识，谁也拿不走。",
    "每多学一样本事，就少说一句求人的话。",
    "做一个温暖的人，不卑不亢，清澈善良。",
    "你的善良和努力，会慢慢变成好运降临。",
    "不必羡慕他人，你也在被别人悄悄羡慕。",
    "自律的人生，才有自由。",
    "请相信，你走的每一步都不会白费。",
    "变好的过程都不太舒服，但熬过来就是蜕变。",
    "不是看到希望才坚持，而是坚持了才能看到希望。",
    "与其焦虑未来，不如把握现在。",
    "你比你想象中更坚强。",
    "悄悄努力，让未来的自己闪闪发光。",
    "书里有光，照亮你未来的每一条路。",
    "聪明是天赋，善良是选择，努力是态度。",
    "勇敢的人，不是不害怕，而是害怕了还在坚持。",
    "不积跬步，无以至千里——但每一步都值得被肯定。",
    "与其等风来，不如追风去。",
    "你的潜力，远超你的想象。",
]

# =============================================================================
# 2. English Inspirational Quotes (with authors)
#    Topics: knowledge, learning, persistence, science, research
# =============================================================================
ENGLISH_INSPIRATIONAL = [
    "The only way to do great work is to love what you do. — Steve Jobs",
    "It does not matter how slowly you go as long as you do not stop. — Confucius",
    "In the middle of every difficulty lies opportunity. — Albert Einstein",
    "Research is formalized curiosity. It is poking and prying with a purpose. — Zora Neale Hurston",
    "The important thing is not to stop questioning. Curiosity has its own reason for existing. — Albert Einstein",
    "Live as if you were to die tomorrow. Learn as if you were to live forever. — Mahatma Gandhi",
    "An investment in knowledge pays the best interest. — Benjamin Franklin",
    "The mind is not a vessel to be filled, but a fire to be kindled. — Plutarch",
    "Science is not only a disciple of reason but also one of romance and passion. — Stephen Hawking",
    "Success is not final, failure is not fatal: it is the courage to continue that counts. — Winston Churchill",
    "I have not failed. I've just found 10,000 ways that won't work. — Thomas Edison",
    "The secret of getting ahead is getting started. — Mark Twain",
    "Education is the most powerful weapon which you can use to change the world. — Nelson Mandela",
    "Imagination is more important than knowledge. Knowledge is limited. Imagination encircles the world. — Albert Einstein",
    "The beautiful thing about learning is that nobody can take it away from you. — B.B. King",
    "Nothing in life is to be feared, it is only to be understood. Now is the time to understand more, so that we may fear less. — Marie Curie",
    "Persistence is the twin sister of excellence. One is a matter of quality; the other, a matter of time. — Marabel Morgan",
    "The more I read, the more I acquire, the more certain I am that I know nothing. — Voltaire",
    "There is no substitute for hard work. — Thomas Edison",
    "Somewhere, something incredible is waiting to be known. — Carl Sagan",
    "The only limit to our realization of tomorrow shall be our doubts of today. — Franklin D. Roosevelt",
    "One child, one teacher, one book, one pen can change the world. — Malala Yousafzai",
    "The expert in anything was once a beginner. — Helen Hayes",
    "You don't have to be great to start, but you have to start to be great. — Zig Ziglar",
    "The roots of education are bitter, but the fruit is sweet. — Aristotle",
    "A person who never made a mistake never tried anything new. — Albert Einstein",
    "Learning is not attained by chance; it must be sought for with ardor and attended to with diligence. — Abigail Adams",
    "Study hard what interests you the most in the most undisciplined, irreverent and original manner possible. — Richard Feynman",
    "We are what we repeatedly do. Excellence, then, is not an act, but a habit. — Aristotle",
    "I was taught that the way of progress was neither swift nor easy. — Marie Curie",
    "The universe is under no obligation to make sense to you. — Neil deGrasse Tyson",
    "Have no fear of perfection — you'll never reach it. — Salvador Dalí",
    "If I have seen further, it is by standing on the shoulders of giants. — Isaac Newton",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. — Nelson Mandela",
    "In science, there is only physics; all the rest is stamp collecting. — Ernest Rutherford",
    "Not everything that counts can be counted, and not everything that can be counted counts. — William Bruce Cameron",
    "Be less curious about people and more curious about ideas. — Marie Curie",
    "It always seems impossible until it's done. — Nelson Mandela",
    "The only true wisdom is in knowing you know nothing. — Socrates",
    "Genius is one percent inspiration and ninety-nine percent perspiration. — Thomas Edison",
    "Tell me and I forget. Teach me and I remember. Involve me and I learn. — Benjamin Franklin",
    "The greatest enemy of knowledge is not ignorance, it is the illusion of knowledge. — Daniel J. Boorstin",
    "Every great advance in science has issued from a new audacity of imagination. — John Dewey",
    "Do not wait to strike till the iron is hot, but make it hot by striking. — William Butler Yeats",
    "What we know is a drop, what we don't know is an ocean. — Isaac Newton",
    "Equipped with his five senses, man explores the universe around him and calls the adventure Science. — Edwin Hubble",
    "The best time to plant a tree was twenty years ago. The second best time is now. — Chinese Proverb",
    "I think, therefore I am. — René Descartes",
    "The capacity to learn is a gift; the ability to learn is a skill; the willingness to learn is a choice. — Brian Herbert",
    "Research is to see what everybody else has seen, and to think what nobody else has thought. — Albert Szent-Györgyi",
    "You are never too old to set another goal or to dream a new dream. — C.S. Lewis",
    "The cure for boredom is curiosity. There is no cure for curiosity. — Dorothy Parker",
    "Creativity is intelligence having fun. — Albert Einstein",
    "If you can't explain it simply, you don't understand it well enough. — Albert Einstein",
    "The noblest pleasure is the joy of understanding. — Leonardo da Vinci",
]

# =============================================================================
# 3. Late-Night Quotes (深夜语录)
#    Warm, not sad, encouraging rest and self-care
# =============================================================================
LATE_NIGHT_QUOTES = [
    "夜深了，记得放下手中的忙碌，好好休息，明天又是新的一天。",
    "今天辛苦了，不管结果如何，你都已经很棒了。晚安。",
    "深夜的努力，白天的你一定会感谢的。但现在，先休息吧。",
    "别熬太晚，身体才是革命的本钱。",
    "夜再深，也要记得：有人在乎你，有人等你回家。",
    "月亮不睡你不睡，你是秃头小宝贝——所以快去睡觉吧。",
    "今天的你，已经足够努力了，允许自己休息。",
    "世界可以等一等，你先好好睡一觉。",
    "学不完的知识明天再学，熬不完的夜今晚别再熬了。",
    "再忙也要记得喝水、吃饭、按时睡觉，这是你对自己最基本的温柔。",
    "深夜的星星在为你亮着，你也要好好爱自己。",
    "你今天的烦恼，睡一觉就会变小。晚安。",
    "夜晚是用来休息的，不是用来焦虑的。",
    "披星戴月的你，终将凯旋。但今夜，先好好睡。",
    "晚安，明天的你一定比今天更好。",
    "别把所有的压力都扛在今晚，你值得一个安稳的觉。",
    "深夜了，把焦虑交给风，把疲惫交给床，你只管安心入睡。",
    "再多的事情，也比不上你的健康重要。早点休息。",
    "夜深了，给自己一个拥抱，你真的很了不起。",
    "做不完的事情，就留给明天精力充沛的自己吧。晚安。",
    "困了就睡吧，梦里什么都有。",
    "你已经比大多数人都努力了，今晚安心睡吧。",
    "每一个熬夜的人都了不起，但更了不起的是懂得适时休息的人。",
    "星星会替你守着夜，你只管闭眼做个好梦。",
    "今晚早点睡，明天才能更有力气追梦。",
]

# =============================================================================
# 4. Morning / Sunrise Quotes (早安语录)
#    Fresh, optimistic, energizing
# =============================================================================
MORNING_QUOTES = [
    "早安！新的一天，新的开始，愿你满怀希望地出发。",
    "太阳升起来了，你也要元气满满哦。",
    "每一个早晨都是一次重新出发的机会。早安。",
    "今天也要加油呀，你是最棒的！",
    "清晨的阳光正好，愿你的心情也一样明媚。",
    "早起的你，已经赢了一大半。",
    "新的一天，请对自己说：我可以的。",
    "一日之计在于晨，今天又是元气满满的一天。",
    "愿你的每一天都像清晨的阳光一样温暖明亮。",
    "早安，去做那个闪闪发光的自己吧。",
    "生活明朗，万物可爱。早安。",
    "又是充满可能性的一天，好好把握吧。",
    "太阳出来了，昨天的烦恼就让它过去吧。",
    "每天醒来都是一份礼物，记得珍惜。",
    "早安！愿今天的你，比昨天多一份从容。",
    "用一杯咖啡唤醒新的一天，用微笑迎接新的挑战。",
    "今天也是值得期待的一天。早安。",
    "清晨的风带来好消息：你又拥有了崭新的二十四小时。",
    "早安，世界很大，机会很多，从今天开始行动吧。",
    "朝阳与你，都是新的。愿你今天一切顺利。",
    "睁开眼，满是阳光；抬起头，满是希望。早安。",
    "新的一天，希望你被这个世界温柔以待。",
    "早安！你今天的努力，是未来回忆里最美的风景。",
    "带着昨天的经验和今天的勇气，出发吧。",
    "阳光正好，微风不燥，你也刚刚好。早安。",
]

# =============================================================================
# 5. Noon / Afternoon Quotes (午间语录)
#    Lunch break, afternoon tea, energy recharge
# =============================================================================
NOON_QUOTES = [
    "中午啦，先放下论文去吃饭吧 🍱 好好吃饭才有力气搞科研。",
    "午饭时间到！吃点好的犒劳一下自己 🍜",
    "忙了一上午了吧？记得补充能量 🧃",
    "中午记得休息一会儿，下午才有好状态 😊",
    "饭后小憩十五分钟，效率翻倍哦 💤",
    "午安！下午继续加油，你已经很棒了 ✨",
    "喝杯奶茶续命吧 🧋 你值得拥有甜甜的下午。",
    "下午茶时间 ☕ 来杯咖啡提提神？",
    "下午犯困很正常，站起来伸个懒腰吧 🙆",
    "下午的阳光好温柔，你也要对自己温柔一点 🌤️",
    "坚持到现在的你，已经超越了大部分人 🌟",
    "午后时光，适合静下心来好好阅读 📖",
    "下午别忘了喝水哦 💧 保持水灵灵的。",
    "如果累了就听首歌吧 🎵 休息也是生产力。",
    "午后小确幸：翻译进度又前进了一点 🎯",
    "工作再忙也要按时吃饭，你的身体最重要 🍚",
    "下午好！今天的你一定会有所收获 🌈",
    "午间休息一下，好的灵感需要放松来酝酿 💡",
    "记得活动一下脖子和肩膀，久坐不好哦 🧘",
    "泡一杯花茶，安静地翻几页论文 🍵 这就是岁月静好。",
    "今天中午吃了什么好吃的？好好享受美食吧 🥗",
    "一天过半，你已经完成了很多，继续保持 💪",
    "午后适合消化新知识，你正在变得更强 📚",
    "别太拼了，适当摸鱼也是一种智慧 🐟",
    "下午好，世界因为有你的努力而更精彩 🌻",
]

# =============================================================================
# 6. Evening Quotes (傍晚语录)
#    Winding down, reflecting on the day
# =============================================================================
EVENING_QUOTES = [
    "傍晚了，今天辛苦啦 🌇 收收心准备下班吧。",
    "夕阳很美，记得抬头看看窗外 🌅",
    "一天快结束了，给自己打个分吧 ⭐ 肯定不低。",
    "晚饭时间到！别亏待自己的胃 🍲",
    "今天又学到了新东西，值得开心 🎉",
    "傍晚的风很舒服，出去走走吧 🍃",
    "今天的任务完成得怎么样？不管怎样你都很棒 👏",
    "回家路上注意安全 🏠 明天又是崭新的一天。",
    "忙碌了一天，晚上犒劳自己一顿好的吧 🍕",
    "日落很美，就像你今天的努力一样闪耀 ✨",
    "收工啦！剩下的交给明天精力充沛的自己 🌙",
    "傍晚适合散步和发呆，给大脑放个假 🧠",
    "今天的进度不错哦，给自己一个大大的赞 👍",
    "下班时间到，该享受生活啦 🎬",
    "又度过了充实的一天，晚上好好放松吧 🛋️",
]
